import { AlertTriangle, CheckCircle2, ChevronDown } from 'lucide-react';
import type { Dataset } from '../../../../shared/contracts';
import { RasterMetadata } from './RasterMetadata';

export function DatasetDetails({ dataset }: { dataset: Dataset | undefined }) {
  if (!dataset) return <p className="query-empty">未选择数据</p>;
  return <div className="dataset-details">
    <h2>{dataset.name}</h2>
    <dl className="compact-metadata">{dataset.kind !== 'raster' && <><div><dt>{dataset.kind === 'table' ? '记录' : '要素'}</dt><dd>{dataset.featureCount.toLocaleString('zh-CN')}</dd></div><div><dt>几何</dt><dd>{dataset.kind === 'table' ? '非空间表格' : dataset.geometryType}</dd></div></>}<div><dt>CRS</dt><dd>{dataset.kind === 'table' ? '不适用' : dataset.crsAuthority ?? (dataset.crsWkt ? '自定义 CRS' : '未知')}</dd></div><div><dt>格式</dt><dd>{dataset.source.driver}</dd></div>{dataset.kind !== 'raster' && <><div><dt>源数据层</dt><dd>{dataset.source.layer}</dd></div><div><dt>来源编码</dt><dd>{dataset.source.encoding ?? (dataset.kind === 'table' ? '不适用' : '自动')}</dd></div></>}{dataset.kind === 'table' && <div><dt>单元格元数据</dt><dd>{dataset.cellMetadataLayer ?? '未附带'}</dd></div>}<div><dt>质量状态</dt><dd className={dataset.report.status === 'restricted' ? 'danger' : 'warning-text'}>{dataset.report.status === 'restricted' ? '受限' : '带警告'}</dd></div></dl>
    {dataset.kind === 'raster' && <RasterMetadata raster={dataset.raster} />}
    <details><summary><ChevronDown size={14} />来源与版本</summary><dl className="stacked-metadata"><div><dt>来源路径</dt><dd><code>{dataset.source.path}</code></dd></div><div><dt>托管快照</dt><dd><code>{dataset.relativePath}</code></dd></div><div><dt>数据版本</dt><dd><code>{dataset.version}</code></dd></div><div><dt>来源指纹</dt><dd><code>{dataset.source.fingerprint}</code></dd></div><div><dt>完整 CRS</dt><dd><code>{dataset.crsWkt ?? '未提供'}</code></dd></div></dl></details>
    {!!Object.keys(dataset.source.metadata).length && <details><summary><ChevronDown size={14} />来源元数据</summary><dl className="stacked-metadata">{Object.entries(dataset.source.metadata).map(([name, value]) => <div key={name}><dt>{name}</dt><dd><code>{value}</code></dd></div>)}</dl></details>}
    <details open><summary><ChevronDown size={14} />导入检查</summary><div className="import-checks">{dataset.report.checks.map((check, index) => <div key={`${check.code}-${index}`}>{check.passed ? <CheckCircle2 size={15} className="success" /> : <AlertTriangle size={15} className="warning-text" />}<span>{check.detail}{check.count !== undefined && <small>数量：{check.count}</small>}</span></div>)}</div>{!!dataset.report.warnings.length && <ul className="data-warnings">{dataset.report.warnings.map((warning, index) => <li key={index}>{warning}</li>)}</ul>}{!!dataset.report.notChecked.length && <><h3>未检查项</h3><ul className="data-warnings">{dataset.report.notChecked.map((item, index) => <li key={index}>{item}</li>)}</ul></>}<span className="muted small">校验器 {dataset.report.validatorVersion}</span></details>
    {dataset.kind !== 'raster' && <details><summary><ChevronDown size={14} />字段定义 · {dataset.fields.length}</summary><div className="field-definitions">{dataset.fields.map((field) => <div key={field.name}><strong>{field.alias || field.name}</strong><code>{field.name}</code><span>{field.sourceType} → {field.storageType}</span><small>可为空：{field.nullable === null ? '未知' : field.nullable ? '是' : '否'} · 精度：{field.precision ?? '未知'}</small></div>)}</div></details>}
  </div>;
}
